baseURL = 'https://mammoth777.github.io/blog/'
languageCode = 'en-us'
title = 'Hoi !'
theme = "hugo-theme-nix"
buildfuture = true
builddrafts = true

[author]
name = '佳琦+7'

[params]
  localSearch = true
  Name = "Jacob"
  HeaderUsername = "jacob"
  HeaderHostname = "jinyu.cool"
  About = "Gooooooood boy"
  ProfilePicture = "https://avatars.githubusercontent.com/u/25866839?s=400&u=aec3e16d03bcd68e7f9c558b9c65c065aed95494&v=4"
  GithubID = "https://github.com/Mammoth777"
  TelegramID = "hoi12138"

[params.utteranc]
  enable = true
  repo = "Mammoth777/blog-discuss"    # 存储评论的Repo，格式为 owner/repo
  issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
  theme = "github-light" # 样式主题，有github-light和github-dark两种

[menu]
  [[menu.header]]
    identifier = "bb"
    name = "随笔"
    url = "/posts/bb/"
    weight = 1

  [[menu.header]]
    parent = "post"
    name = "all_posts"
    url = "/posts"

  [[menu.header]]
    parent = "post"
    name = "categories"
    url = "/categories"

  [[menu.header]]
    parent = "post"
    name = "tags"
    url = "/tags"